### ISSUE TITLE
Migrate structopt to clapv3

### ISSUE THREAD

**Issue by rahul-thakoor** [balena-os/takeover#50]
https://github.com/balena-os/takeover/blob/f37c754877392fe9bdca174b9dce6a1b637147ec/Cargo.toml#L25

- structopt is in maintainance mode and has not been updated since 18.01.2022
- https://github.com/TeXitoi/structopt?tab=readme-ov-file#maintenance
- no new features will be added
- https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating

**Comment by lmbarros** [comment]
Solved by #56
