### ISSUE TITLE
Device passed to `--log-to` is checked only when already entering stage 2

### ISSUE THREAD

**Issue by lmbarros** [balena-os/takeover#57]
This is an usability issue. If I pass an invalid value to `--log-to`, I get a warning only after `takeover` is already entering stage 2, so I can't safely stop the process and fix my mistake.

Ideally, the validity of the argument should be checked earlier on. And I guess that by default (unless we also pass `--no-ack`?) we should stop the execution if the argument is not valid.

**Comment by rahul-thakoor** [comment]
closed by #78
